### ISSUE TITLE
Replace the usage of SharedPreferences.getInstance() Riverpod Provider

### ISSUE THREAD

**Issue by mohit92** [meditohq/medito-app#110]
when you do SharedPref,getInstance(), it is an async function even if it returns the same instance every time. This results in a async function everytime we need to read/write data to shared prefs and becomes difficult to deal with in widgets.

now since we store this instance at first page, we don’t need to call the async getInstance method every time and can access sharedprefs in a sync manner. You can check the usage of it in markAsListened method.

**Comment by michaelcspeed** [comment]
Getting info from SharedPrefs can be coverted into Riverpod providers. 
We can have one that injects SharedPrefences, then multiple for each but of information that we need to provide.

**Comment by scouech** [comment]
@michaelcspeed is that done?

**Comment by michaelcspeed** [comment]
@osamaasifoak ?

**Comment by scouech** [comment]
@osamaasifoak can you give an update on this for everyone? Cheers

**Comment by osamaasifoak** [comment]
Hi @scouech @michaelcspeed Previously we were creating the sharedPref instance on the main function and were using it all over the application via global variable. I started working on it and it will be migrated to a Riverpod provider within a day or 2.

**Comment by scouech** [comment]
@osamaasifoak what's the status on this? Cheers

**Comment by AleksandrTaranzhin** [comment]
🙏

**Comment by scouech** [comment]
@osamaasifoak can you explain roughly what has been done please, so that I can close the ticket. Cheers

**Comment by osamaasifoak** [comment]
@scouech Previously, we used a global instance of shared preference. Now, I created a Riverpod provider to obtain an instance of shared preference.
