### ISSUE TITLE
Order narrator/voice

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#122]
**Screen:** Player option screen

**Affects:** Narrator row

**Currently:** The narrators/voices are returned in a random order.

**Expected behaviour:** We should order narrators from Z to A. 
So if we have Steven, Will, Tiffany, we will get Will, Tiffany, Steven.

**Comment by michaelcspeed** [comment]
https://github.com/meditohq/medito-app/blob/6501aa5769ab602b3e6cd6baf6a6c5c5aa07432c/lib/network/session_options/session_options_bloc.dart#L76
