### ISSUE TITLE
App stops loading audio file after screen gets turned off

### ISSUE THREAD

**Issue by behradkhadem** [meditohq/medito-app#126]
Hi and thanks for your good app.
Whenever I'm having an unguided meditation, after a certain time it stops downloading the audio file from internet. And when I unlock my phone after some time, it starts counting time from 10:00 (for a 10 min session) and I don't hear second bell sound. When I set a timer, at 10 minute mark phone starts ringing but apps gets shut down. I think this problem can be solved by keeping the screen on during the meditation. 

Keep up the good work.

PS: I'm not sure that unguided meditations are audio files are not, but I'm certainly sure that they don't work on my Huawei Y7 Prime 2019.

**Comment by ansh-les** [comment]
I have faced the same issue. I got so confused as to why my meditation timer never went off. 
My device is OnePlus Nord

**Comment by scouech** [comment]
hey @behradkhadem & @ansh-les 
we are rolling out the new update from today. Once you have got it would you mind letting me know if you still experience the same problem? Thank you!

**Comment by behradkhadem** [comment]
> hey @behradkhadem & @ansh-les 
> we are rolling out the new update from today. Once you have got it would you mind letting me know if you still experience the same problem? Thank you!

Sure! I checked now but I didn't see anything on Google play.

**Comment by scouech** [comment]
It's being rolled out so it might take a while to show up on your side :)

**Comment by scouech** [comment]
I will close this ticket as we have done a lot of changes to the screen / app. Feel free to re-open an issue if you still encounter the problem :) Cheers

**Comment by behradkhadem** [comment]
Hello everyone, I updated app to new version few days ago and I'm testing it since. It's the same and problem still exists. When there is no background sound, app stops loading and playing and closes it. I have this problem in "Daily Meditation" and "Meditation Timer", and other segments work properly, even without background sound.
