### ISSUE TITLE
Create downloadable APK

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#132]
If we could (automatically?) generate a downloadable APK that we could host on github it would be fantastic!

**Comment by harshadmanglani** [comment]
https://medium.com/mobile-development-group/github-actions-for-flutter-cf02923d7b5d

Found this @scouech 
What I can do is try setting this up in my cloned personal medito repo, and once I work out the kinks I'll let @michaelcspeed and @scouech know, we can talk more then

**Comment by scouech** [comment]
amazing @harshadmanglani ! Keep us posted, and if you need anything just ping us of course :)

**Comment by harshadmanglani** [comment]
Update: I was able to figure out how to get it to work on GitHub, but we're having some trouble with the keystore required to generate the APK, that might take a while to resolve.

**Comment by porfirioribeiro** [comment]
Hey @harshadmanglani, i just read [this article](https://andreytreyt.medium.com/sign-and-upload-apk-file-of-flutter-application-with-github-action-91f4dc60daab), maybe it helps?

**Comment by harshadmanglani** [comment]
Hey @porfirioribeiro thanks, checking it out right now!

**Comment by scouech** [comment]
@qtdzz @porfirioribeiro  any luck? :)

**Comment by qtdzz** [comment]
@scouech Here is my attempt https://github.com/meditohq/medito-app/pull/187. Hopefully it works.

**Comment by michaelcspeed** [comment]
This is complete now, thanks to @qtdzz. When I create a new play store release, an apk will be uploaded here 
https://github.com/meditohq/medito-app/releases
