### ISSUE TITLE
Weird flickering when closing background sound bottom sheet

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#148]
1. Play a session
2. Tap on the background sound icon
3. Close the bottom sheet by dragging it down
4. You will notice a weird flickering / ripple effect

I think it's a default behaviour but it looks odd.. I don't know if we can just remove the effect so that it doesn't show? 

**DEVICES**
Pixel 2 XL

**Comment by noesnaterse** [comment]
I cannot reproduce this. 
1. I play a session
2. Tap the background sound icon.
3. The screen goes a bit darker to focus on the background sound sheet. 
4. I drag the bottom sheet down again.
5. The sheet goes down and the screen will become brighter again in one fluent motion.

I am doing this on a Samsung A40 running Android 11.

**Comment by michaelcspeed** [comment]
@scouech could you attach a video of what you mean please?

**Comment by scouech** [comment]
Sure.

See attached.

You can see a ripple effect at the top of the bottom sheet when closing it. It looks quite weird/really obvious. Kinds of feel slow too?

 https://user-images.githubusercontent.com/26603052/119531561-57204f00-bd84-11eb-9989-080c02f8ad9e.mp4

**Comment by noesnaterse** [comment]
Aha, I didn't even notice that. Had to view the video a couple of times to see it. 
To be clear, it the the sheet that goes down really jerky right?
That happens to me too :)

**Comment by scouech** [comment]
Yes correct :)

**Comment by noesnaterse** [comment]
https://user-images.githubusercontent.com/1178741/121779647-076fbf00-cb9d-11eb-871e-93b547cb0769.mp4

Here it still happening, or is this better?

**Comment by scouech** [comment]
I don't think anything was changed right?

-------- Original Message --------

**Comment by noesnaterse** [comment]
Oh, it is better? Because I was wondering how to approach this ticket....
What I did is throw in a TransitionAnimationController, but I also noticed that the frame rate just drops below 60FPS on the transition. I don't know how to solve this.

**Comment by scouech** [comment]
hey @noesnaterse any luck finding out a fix?

**Comment by scouech** [comment]
hey @noesnaterse , any update ?
