### ISSUE TITLE
Better offline message

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#156]
We have moved the downloads, and they are now showing on the home screen. 
If I go offline, the home screen shows me an error message with a `Try again` button.

**To reproduce:**
1. Turn airplane mode on
2. Open the app

Problem:
I can't open my downloaded sessions because it's on the -now inaccessible- home screen.

**Potential solution:**
Next to the `Try again` button, we could display a button that says `Show downloads`. This button would open the `downloads` screen.

If you have a better idea let me know :)

**Comment by michaelcspeed** [comment]
button added here 4ea78e0df765436a2b74ad4b8e33bc16dfd5e2f8
