### ISSUE TITLE
Re-order downloads

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#157]
A few people have asked to have the option to re-order their downloaded sessions. 
We can have a simple drag and drop behaviour to allow re-ordering the list?

I don't think we need to make it obvious...having it as an hidden feature is fine in my opinion. 
If you think it's better to indicate it somewhere, we could use the snackbar we are already using to indicate how to delete a downloaded session and tweak the message to mention the re-ordering..?

**Comment by mic-ray** [comment]
@scouech Maybe a small icon to the right of each downloaded session, which would indicate that the items can be re-ordered, 
 would be an idea? As an example: https://material.io/archive/guidelines/assets/0Bx4BSt6jniD7X0pmWjRNZ21UUFE/components-listcontrols-reorder.png.
 
To comply with your idea of not having it to obvious, maybe these icons only appear once you enter a "list editing mode"? Though i am not sure, whether such a mode is a planned (or even useful) feature.

**Comment by scouech** [comment]
hey @mic-ray , good idea yeah! The "edit mode" thing is a good idea. Maybe a first iteration would be without it, so you can hold and grad to reorder, and then second iteration we could do with an edit mode / icons maybe? Just thinking in terms of making it easy for the dev

**Comment by mic-ray** [comment]
I like the drag and drop idea as a first iteration. Maybe I could try to implement this using the [ReorderableListView](https://api.flutter.dev/flutter/material/ReorderableListView-class.html) widget?

**Comment by scouech** [comment]
sure! Sounds good @mic-ray :)

**Comment by scouech** [comment]
@michaelcspeed if you could review @mic-ray PR would be nice :)
