### ISSUE TITLE
Remember last selected Voice

### ISSUE THREAD

**Issue by michaelcspeed** [meditohq/medito-app#159]
When selecting a voice and starting a session, the app should remember your choice and the next time you open a session, if that narrator is available, the length options for that voice should be expanded.

For example in this screen, the last selected voice would have been Morgan:
<img width="200" alt="Screenshot 2021-05-25 at 19 06 57" src="https://user-images.githubusercontent.com/4272338/119539365-61dee200-bd8c-11eb-9dde-d69736207d6f.png">

Currently only the first narrator in the list is expanded
See `lib/network/session_options/session_options_bloc.dart` line 164

**Comment by DeveloperAlfa** [comment]
I'm willing to pick this up

**Comment by michaelcspeed** [comment]
Thanks @DeveloperAlfa  The UI is different to how it is shown here now, but the principle should be the same (if not easier :) )

**Comment by DeveloperAlfa** [comment]
Question on this, what is the unique identifier of a voice artist?

**Comment by michaelcspeed** [comment]
Check out `lib/network/session_options/session_options_bloc.dart` and `lib/network/session_options/session_opts.dart`
Each Session has a `SessionData` file, which has a list of `AudioFile`s. Each `AudioFile` has a unique id and a related voice string and Length string. So there's no id for a voice artist, just an audio file.

**Comment by michaelcspeed** [comment]
So in fact all we need to do no is save the id of the selected audio file and reselect that one when the screen loads.

**Comment by DeveloperAlfa** [comment]
Created a new PR for fixing this. Sorry I had a confusion about the save id last time!
