### ISSUE TITLE
Fix layout of Homepage on tablet/landscape mode

### ISSUE THREAD

**Issue by michaelcspeed** [meditohq/medito-app#170]
**Describe the bug**
Layout is bloated on tablets in landscape mode. Specifically the shortcuts at the top of the homepage

All devices 

![image](https://user-images.githubusercontent.com/4272338/122927995-b5cbef00-d369-11eb-9d4b-ba679c05e7d1.png)

**Comment by harshadmanglani** [comment]
What should it look like instead?

**Comment by michaelcspeed** [comment]
Doesn't matter too much to me as long as they're not huge haha Maybe 4 short tiles across? @scouech ?

**Comment by harshadmanglani** [comment]
```
var isLargeScreen = false;
return OrientationBuilder(builder: (context, orientation) 
{
            if (MediaQuery.of(context).size.width > 600)
                isLargeScreen = true;
            else
                isLargeScreen = false;

            return isLargeScreen ? portaitWidget : landscapeWidget;
}

```
want me to go ahead and do this?

**Comment by michaelcspeed** [comment]
Yeah that would be great, thanks @harshadmanglani !

**Comment by harshadmanglani** [comment]
will do!

**Comment by harshadmanglani** [comment]
This is what it looks like, I've opened a PR, let me know

https://user-images.githubusercontent.com/47568882/130326875-ed40fe5a-fd2d-45d3-9b6c-935d1241c31c.mp4

**Comment by harshadmanglani** [comment]
Could someone please close this if there are no more concerns?

**Comment by scouech** [comment]
looks nice! thanks @harshadmanglani !
