### ISSUE TITLE
Following Session Option Screen changes

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#182]
- [x] Font size for labels (Pick a narrator.. Download..) seems wrong
- [x] If narrator is "none", don't add extra padding / remove empty space (see timer) 
- [x] Last chip of scrollable durations has less padding than first chip (see timer duration row)
- [x] Option screen: Title is supposed to be on the right of the cover image 
- [x] Folder screen: Title is supposed to be on the right of cover image too
- [x] Folder screen: Extra padding has been added between title / description?
- [x] Option screen > Download area: Dash between name and duration should be the same one as the download screen (long one)
- [x] "begin" text color should be secondary color from data, or if null / empty should be black (see Sleep > Meditation > Getting back to sleep = begin is black on dark rather than secondary color on dark)

**Comment by michaelcspeed** [comment]
9f99b259eade9c0b513b2aeb4caf2ed06c3e9f28
