### ISSUE TITLE
[BUG] white banner during and after meditation not full width

### ISSUE THREAD

**Issue by legrk** [meditohq/medito-app#189]
**Describe the bug**
The white banner during and after a guided meditation is not shown in full width, in contrast to other elements on the same screen. It is aligned on the left hand side of the screen. Occurs on a Android Galaxy Tab in landscape mode.

**To Reproduce**
1. Go to any meditation
2. Click on play button
4. See issues during playback and also in the screen after playback ended

**Expected behavior**
The white banner during and after a guided meditation is shown in full width (or centered?)

**Screenshots**
See attached screenshots.
![Screenshot_20210720-180931](https://user-images.githubusercontent.com/1462755/126763678-75587c36-8be1-4e64-ab4b-18ff822de764.png)
![Screenshot_20210721-171700](https://user-images.githubusercontent.com/1462755/126763685-3bb0b239-fdf0-4a15-9bae-be27763341d4.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab 10.2 (n2awifi)
 - OS: Android 7.1.2
 - Version: 1.0.65 Build 20008

**Additional context**
Thanks for the great app and all your efforts.

**Comment by michaelcspeed** [comment]
Thanks for this @legrk ! 
This image doesn't exist anymore in the newest version, but we should still check what it looks like in landscape mode. Could you update to the newest version and update here if it still needs work? Thanks!

**Comment by legrk** [comment]
I will update this issue, once I get the updated app. So far it did not arrive for me in the PlayStore.

**Comment by legrk** [comment]
I can confirm this is no longer an issue. So far I haven't noticed any issues on my devices.
Nice redesign!
