### ISSUE TITLE
"Pick a narrator & duration" based on context

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#190]
When you open "timer" it says "pick a narrator and duration", but timer does not have a narrator. It should say "pick duration". 
That should be the case for any session with no narrator (none)

**Comment by mic-ray** [comment]
@scouech Do you mind if i take a look at this? 😄

**Comment by scouech** [comment]
Sure @mic-ray  :) Let me know if you need more info!

**Comment by scouech** [comment]
@mic-ray any updates ? :)

**Comment by mic-ray** [comment]
@scouech I am sorry i wasn't able to tackle this earlier. Is it okay with you if i will attempt to solve this (or atleast take a look on it, if i run into problems) during this weekend, or is that too late for you? :)
