### ISSUE TITLE
Background image not displayed on folder screen

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#191]
A folder has a little illustration with an optional background image and a solid color. 
It seems the background image doesn't display anymore (see loving kindness course for example)

**Comment by michaelcspeed** [comment]
Confirmed. Notice the backgrounds of the images here look different

![IMAGE 2021-09-10 10:05:55](https://user-images.githubusercontent.com/4272338/132821432-923e511e-4a88-4bf7-b1f1-4cd44eeab20b.jpg)
![IMAGE 2021-09-10 10:05:56](https://user-images.githubusercontent.com/4272338/132821436-77ed2063-edd0-46e8-917f-847e41b720c7.jpg)

**Comment by michaelcspeed** [comment]
Fixed in e7c44b8fdb971163fed97f43ecc587fa910b597d
