### ISSUE TITLE
Padding missing on session option screen

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#192]
On the session option screen, if there is no description the padding should still be there below the image (see screenshot). 

Example:
UCLA > Spanish > Any session there

![image](https://user-images.githubusercontent.com/26603052/129865048-0d395e6c-3663-4605-908f-d8a8ab39449b.png)

**Comment by harshadmanglani** [comment]
I can do this if that's okay?

**Comment by harshadmanglani** [comment]
Done, I pushed the changes, it'll get reflected in the already open PR :)
![WhatsApp Image 2021-08-27 at 2 58 47 PM](https://user-images.githubusercontent.com/47568882/131105877-08ec25ba-711b-43a8-adac-ae5ac20950da.jpeg)

**Comment by scouech** [comment]
thanks @harshadmanglani :) @michaelcspeed when you have some time if you could review the pR :) Cheers!

**Comment by michaelcspeed** [comment]
Done! Thanks so much @harshadmanglani !!
