### ISSUE TITLE
Slack Channel link doesn't work anymore

### ISSUE THREAD

**Issue by Momen-Shili** [meditohq/medito-app#209]
Slack Channel link doesn't work anymore 
(This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.)

**Comment by scouech** [comment]
hi @Momen-Shili , thanks for letting us know. We are discontinuing the use of slack for general users and will now be using it only for volunteers. Closing this issue :) 
If you want to volunteer, check 
[https://meditofoundation.org/volunteer](https://meditofoundation.org/volunteer)
