### ISSUE TITLE
[BUG] How to get an API key? Slack link was closed on the Code page. 

### ISSUE THREAD

**Issue by desunny** [meditohq/medito-app#226]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Version [e.g. 22] (to see the version number double tap on the Medtio logo on the home page of the app)

**Additional context**

**Comment by michaelcspeed** [comment]
Hey @desunny, sorry about the slow reply. We had to stop accepting Slack members because we were reaching the limit at which we'd have to pay. If you still want to help you can email me mike[at]meditofoundation.org
Cheers!
