### ISSUE TITLE
Auto play session when tapping on "Begin" on session option screen

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#235]
We have received feedback multiple times now. It would better better from a UX perspective to start the audio when you tap "begin" from the session option screen. 
In most cases the background sound will be selected (if any), otherwise they can change it anyway once the audio has started.

**Comment by DeveloperAlfa** [comment]
I'll take this :+1:

**Comment by DeveloperAlfa** [comment]
Here is the PR: https://github.com/meditohq/medito-app/pull/236

Tested on my device. Kindly review.

**Comment by michaelcspeed** [comment]
Nice thanks @DeveloperAlfa !
