### ISSUE TITLE
Format for email support

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#242]
Could we format the first part of the email this way (while trying to keep the formatting, especially now we are using Plain, because otherwise it's all mixed up)

> ------ 
> Version: {{Version ID}}
> Device: {{Device type / OS number}}
> ID: {{User ID}}
> ------ Please write your email below this line ------

**Comment by athJ** [comment]
I think we should have a similar format for github issues are well .
Atleast version and device should be mentioned with the issues.

**Comment by michaelcspeed** [comment]
Fixed in develop. Will be in v2.0.39
