### ISSUE TITLE
Continue where you left off

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#243]
> one feature that
> I think would be super useful is adding a section that shows the current
> courses/packs you are working on.  There is so much content (which is
> amazing) I sometimes try to remember which pack I am working through, so it
> takes me some time to find it and then continue.
> 
> It would be great if you could add something like Netflix has such as a
> "Continue listening..." area where for example it shows you are partially
> complete the "30 day challenge" and you can tap on that to bring you
> quickly to the next one you haven't completed "Day 14" and other packs you
> have started working on without having to searc

**Comment by nixbitpie** [comment]
I agree. This could be as simple as replacing the play icon with a checkmark icon in front of the titles, after they've been played.

**Comment by michaelcspeed** [comment]
This has been added to our feature request list. Thanks!
