### ISSUE TITLE
Time elapsed incorrect when a session is playing

### ISSUE THREAD

**Issue by garethyorke** [meditohq/medito-app#256]
Issue from someon on Instagram - time elapsed says 10 mins a few seconds in.

Screen shot attached.

I've asked them to confirm what device they are using
![photo_2022-04-09 11 24 26](https://user-images.githubusercontent.com/66156346/162567949-3384736f-7f07-4bcd-958d-0503f4bfa96a.jpeg)

**Comment by michaelcspeed** [comment]
Can't reproduce this anymore. Can reopen if it happens again
