### ISSUE TITLE
[BUG] BG sound volume is broken

### ISSUE THREAD

**Issue by michaelcspeed** [meditohq/medito-app#257]
**Describe the bug**
Volume keeps jumping around, being loud and quiet

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a session
2. Play bg sounds 

**Expected behaviour**
The volume should stay the same level

**Comment by ssaurab** [comment]
I can reproduce this behavior (iOS).

Especially at the start of each session with a pre-selected bg sound, the initial volume is abnormally high.

**Comment by michaelcspeed** [comment]
Fixed on develop. Will be in v2.0.39
