### ISSUE TITLE
The progress bar no longer works when you turn back the time 

### ISSUE THREAD

**Issue by raffing** [meditohq/medito-app#259]
When you move the audio progress bar back, after the dot no longer moves but only time is pushed forward and the ball remains stationary.
![Screenshot_2022-04-18-09-15-29-095_meditofoundation medito](https://user-images.githubusercontent.com/8293710/163772770-a05b3ae2-d99c-4dc5-a4bd-09c6500a5d47.jpg)

**Comment by michaelcspeed** [comment]
Fixed on develop. Will be in v2.0.39
