### ISSUE TITLE
Add backup functionality

### ISSUE THREAD

**Issue by Granddave** [meditohq/medito-app#261]
A way of backing up user progress for such a nice app like this is IMO an important feature - almost a deal breaker for me.

Haven't seen any discussion about this after a quick search, please direct me to any discussion if it already has been taken place.

**Proposal:**
A simple file backup to local storage that either can be triggered manually or run automatically and save the last X backups together with a similar restore functionality.

**Comment by ghost** [comment]
You can back up app data with Google one in android.

**Comment by nixbitpie** [comment]
It would be nice to have alternatives other than Google One for backup.

**Comment by RomanHauksson** [comment]
[Neo Backup](https://github.com/NeoApplications/Neo-Backup) or [Seedvault](https://github.com/seedvault-app/seedvault) might work as alternatives.

**Comment by ghost** [comment]
> [Neo Backup](https://github.com/NeoApplications/Neo-Backup) or [Seedvault](https://github.com/seedvault-app/seedvault) might work as alternatives.

Neo backup requires root and not sure how to use seedvault.
I want to use the fdroid version of Medito, but can't transfer data even with Google backup. So, I also would like to see a way to import/export stats.

**Comment by michaelcspeed** [comment]
We will probably implement accounts at some point, or maybe just a CSV export. This has been added to our feature request list. Thanks!
