### ISSUE TITLE
IOS background audio not playing issue

### ISSUE THREAD

**Issue by AzimLalan** [meditohq/medito-app#262]
Users complained the background audio stops

Battery drain issue
User email:
It is still draining my phone to 0%, if I forget to Force Stop it before falling asleep. Please investigate this issue!

**Comment by michaelcspeed** [comment]
This is also an issue on Android it seems. I think a stream must not be disposed of somewhere

**Comment by michaelcspeed** [comment]
fixed on dev. will release in 2.0.39
