### ISSUE TITLE
Slack channel link doesn't work

### ISSUE THREAD

**Issue by ghost** [meditohq/medito-app#264]
Hey guys,

I just tried to join the Slack channel using the link in README.md, but Slack tells me that "This link is no longer active".

Can somebody please update the link?

Thank you! 🙌🏼

1. ![image](https://user-images.githubusercontent.com/55190118/166420491-05b4bb6f-c842-4c07-b867-b0d710dd0206.png)
2. ![image](https://user-images.githubusercontent.com/55190118/166420537-afb52b1b-42a8-4bf3-824d-e8bf12c1a69e.png)

**Comment by michaelcspeed** [comment]
We have reached capacity in our Slack channel, but we'll be removing some inactive users soon so please check back in a few weeks if you'd like to join. :)
We've updated the readme
