### ISSUE TITLE
Cannot play Spotify music along with Medito

### ISSUE THREAD

**Issue by AzimLalan** [meditohq/medito-app#265]
User email!

I used to be able to listen to Spotify, for ambient sounds/music, at the
same as I was using Medito but unfortunately it doesn't work anymore. Now
when I put something on Spotify, it pauses the Medito meditation (and if
I try it the other way round it pauses Spotify, which was already the case
before though).
I'd love it if the option to listen to both of them at the same time again
came back.

**Comment by michaelcspeed** [comment]
Fixed on develop. Will be in v2.0.39
