### ISSUE TITLE
Audio Issue: Abrupt end of a session

### ISSUE THREAD

**Issue by AzimLalan** [meditohq/medito-app#266]
we have received the below feedback:
I'm a regular user of your app. I really like it overall, but you've made a recent change I dislike: now the sounds (rain, waves, river) that I can select to accompany a meditation end very abruptly with the end of a session, whereas they used to fade gradually. I find the abrupt end of the sound a very jarring way to end my meditation session.  (I use the unguided timer option most often.)
I am sure there are reasons for the change, but I wanted to offer this feedback in case you're also hearing it from others. Thanks!

**Comment by michaelcspeed** [comment]
Fixed on develop. Will be in v2.0.39
