### ISSUE TITLE
[BUG] Deep links don't work on iOS

### ISSUE THREAD

**Issue by michaelcspeed** [meditohq/medito-app#267]
Deep links don't work at all on iOS but they do on Android. Scheme on iOS is currently `customscheme` but should be https:// if possible

version 2.0.37

**Comment by scouech** [comment]
@osamaasifoak when you have a chance, if you could look at this - I don't know if it was fixed previously or not. Cheers

**Comment by scouech** [comment]
Closing this ticket as we will create a new one for deep links across both platforms.
