### ISSUE TITLE
[BUG] Slider position does not update its position

### ISSUE THREAD

**Issue by andrasferenczi** [meditohq/medito-app#268]
**Describe the bug**
When listening to a meditation session, the audio is playing, the seconds are updated, but the slider position is not adjusted.

**To Reproduce**
1. Start a session, don't go anywhere
2. Click on the slider to go to a position
3. See that the slide does not move

**Expected behavior**

**Screenshots**

<img src="https://user-images.githubusercontent.com/17592224/170841956-c0587736-54c1-43eb-ae6d-61a520e7a01a.jpg" width="300">

**Smartphone (please complete the following information):**
 - Device: Galaxy A5 2017
 - OS: Android 8
 - Version: 2.0.37 - Build Number: 20037

**Additional context**

**Comment by michaelcspeed** [comment]
Can you please check the version number? You have to long press the Good Afternoon/Morning text on the main page (I will update the instructions now)

**Comment by andrasferenczi** [comment]
I got it, updated the issue accordingly.

**Comment by michaelcspeed** [comment]
OK could you please update to the latest version [v2.0.42] and retest?

**Comment by andrasferenczi** [comment]
This is the latest available version for me from the play store.

Edit.: Do you mean I should download the latest release from Github (the apk)?

**Comment by michaelcspeed** [comment]
The latest version on the Play Store should be 2.0.48 - not sure why you're seeing an old version. Please feel free to open this again if it is reproducible on the latest version. Thanks!

<img width="696" alt="Screenshot 2022-07-25 at 17 00 07" src="https://user-images.githubusercontent.com/4272338/180808521-935e5519-9eab-4dd0-b7f3-c306ced911bd.png">
