### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by rishiba** [meditohq/medito-app#270]
**Describe the bug**
In 30 Day Challenge pack - when I listen to a meditation and complete it fully - the streak is not marked. The day is not ticked complete.

**To Reproduce**
1. Go to '30 DC Pack'
2. Click on 'Any day for example day 1 day 2'
3. Complete the meditation (either sit for 20 mins or scroll the slider to 19:55 mins and wait for it to complete)

**Expected behavior**
The day of the meditation should be marked as done or a tick should come.

**Screenshots**

Please see the recording here - https://drive.google.com/file/d/1sN25X4wJCq057x_gpG5YkFsA2eiL47UQ/view?usp=sharing

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samasung Galaxy Note 10 Lite
 - Version [e.g. 22] (to see the version number long press the Good Morning/Afternoon text on the home page of the app)
 - 
![image](https://user-images.githubusercontent.com/7330438/172356474-8f69ab45-7f42-4b15-a80f-54a6d317e40f.png)

**Additional context**

**Comment by michaelcspeed** [comment]
Thank you for the thorough bug report @rishiba . This issue is now fixed and will be released in the next version (which will be 2.0.45)

**Comment by rishiba** [comment]
Do we have any workaround for this?

**Comment by michaelcspeed** [comment]
> Do we have any workaround for this?

Yes you can edit the streak by tapping on it, or swipe on the session to mark it as listened to
