### ISSUE TITLE
Daily reminder to meditate

### ISSUE THREAD

**Issue by MakeGnomeWebFast** [meditohq/medito-app#271]
It could be awesome to have a daily reminder notification in the app that suggests you to meditate. Better yet, integrate it with the quote inside the app so that Medito sends a notification like Time to meditate! + the daily quote.

**Comment by saralaya00** [comment]
+1 This is something I miss after moving from waking up app

**Comment by michaelcspeed** [comment]
Please request new features by emailing us. We don't have a good process for this yet unfortunately, but Github Issues is for bugs. Thanks!

hello@meditofoundation.org
