### ISSUE TITLE
Only one session playable until complete app restart - F-Droid

### ISSUE THREAD

**Issue by raycadle** [meditohq/medito-app#272]
Pretty much the title. After listening to the first welcome session, I could no longer listen to anything in the app—nothing plays. I had to completely close the app before anything would play, and then the issue happened again. The app seems great so far, but this bug makes it a bit unusable.

**Comment by highvortex** [comment]
+1
This however is only in f-droid version, the play store version doesn't have this problem.

**Comment by nixbitpie** [comment]
+1 Also F-Droid.

**Comment by michaelcspeed** [comment]
Please contact the maintainer of the F-Droid repo. The FDroid fork needs to be updated by them.
Let's keep this page for issues with the main repo. :)
