### ISSUE TITLE
feature: Add an interval timer into the regular timer

### ISSUE THREAD

**Issue by VladMasarik** [meditohq/medito-app#282]
Would it make sense to add an interval timer that would ring during the regular timer?

Eg. I usually set a normal timer for X minutes. But then I always want an extra gong or two every 3 minutes so that I am reminded to stop wondering around.

Right not you can set only the total time, but no interval timer. Something along the lines of here
https://www.meditation-timer.com/
https://github.com/brenjamin/meditation-timer

I might actually be able to create a PR myself, but if you were able to do it 10x faster, then I would ask first

**Comment by jonathan-s** [comment]
I would also like to see this. Also right now there is no free form timer. The max you can set is 60min you might want to set 120 min or 45 min or some other odd number.
