### ISSUE TITLE
feature: Use more flexible timer selection

### ISSUE THREAD

**Issue by VladMasarik** [meditohq/medito-app#283]
The possibility to choose 3, 5, 8, 10 ... minute timers is great, and covers most of the cases, but could we include a "time selector" like the ones you have on an alarm? Or like on this website?

https://www.meditation-timer.com/
https://github.com/brenjamin/meditation-timer

**Comment by scouech** [comment]
Will add this as a backlog ticket under "Projects". It's also available on Discussions. Cheers
