### ISSUE TITLE
Feature request: Integration with HealthKit

### ISSUE THREAD

**Issue by zsolt-dev** [meditohq/medito-app#285]
Benefits:
- Track meditations in healthkit (accross multiple meditation apps)
- Track heart rate during metitation.
If you report to healthkit that a meditation is in progress, it starts HR monitoring on Apple Watch. This is usefull for heart rate variability changes and for calculating the difference at the meditation start and end.

I know this might be a niche and wont be high in the priorities list, but just leaving it here as an idea.

Thank you

**Comment by shubham08gupta** [comment]
I would love to see this feature. It will help me track my meditation time in Apple Health app.

**Comment by CodinMoldovanu** [comment]
I'd be interested in helping bring this forward a bit.

**Comment by scouech** [comment]
Thanks all. This topic was already open under "Discussions" Closing this as it's not an issue. Cheers

**Comment by lambdakilo** [comment]
For anyone wandering here: https://github.com/meditohq/medito-app/discussions/93
