### ISSUE TITLE
[BUG] Sometimes minutes listened duplicates for daily meditations

### ISSUE THREAD

**Issue by TheRealWHfan** [meditohq/medito-app#288]
**Describe the bug**
Sometimes double the minutes of a meditation session is added onto minutes listened. For example if i listen to a 15 minute meditation session in the daily meditation section 30 minutes will be added to minutes listened.

To reproduce the bug please listen to a few daily meditations of varying lengths and then look at the time added to minutes listened after each listen. It doesn’t always double the time added.

**Smartphone (please complete the following information):**
 - Device: iPhone 6s Plus
 - OS: iOS14.4
 - Version 2.0.47

**Comment by scouech** [comment]
@TheRealWHfan, the new app version (coming in the next few weeks) fixes this issue. 
Thanks for reporting :)
