### ISSUE TITLE
Integrate UPI for Indian donations 💖

### ISSUE THREAD

**Issue by DevChaudhary78** [meditohq/medito-app#292]
today, as a long-time user of this app, I decided to donate to the cause of Medito. when I went to the donation page, I saw stripe as a payment method. however, as an Indian, UPI is a way more efficient method of donating money with one click. 

UPI: is a Unified Payment Interface, made by the Indian Govt. to ease online transactions from bank to bank.

Note: I know it might be tough for the devs to go through UPI, as UPI might not be supported in the country, however, this is just a suggestion, if implemented well, it can increase the donations (specially micro-donations) drastically.

**Comment by akash-258** [comment]
My cards have failed multiple times when I tried donating.
I had same problem when trying to buy spotify premium using cc, but it when super smooth with upi. So, I think if its possible it would be very helpful.

**Comment by scouech** [comment]
Thanks both! Unfortunately we can't implement that due to local regulations. You can always use [paypal](https://paypal.me/meditofoundation) or our updated donate form, for now available here: [donate.meditofoundation.org](https://donate.meditofoundation.org). Thanks for your support!
