### ISSUE TITLE
[BUG] Stream via https for privacy

### ISSUE THREAD

**Issue by erebion** [meditohq/medito-app#297]
**Describe the bug**

Audio seems to get streamed via HTTP, which is bad for privacy.

**To Reproduce**
1. Block clear text communication on an Android ROM that supports it or use a firewall to block port 80
2. Try to stream audio
3. Audio does not start playing, downloads do not work, just the player *seemingly* playing, but no audio and the progress bar does not move.

**Expected behavior**

Audio should be streamed and downloaded via HTTPS for privacy reasons.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] not relevant
 - OS: [e.g. iOS8.1] not relevant
 - Version [e.g. 22] (to see the version number long press the Good Morning/Afternoon text on the home page of the app) not relevant

**Additional context**
Just think of all the countries where literally any info will get used against you.

**Comment by scouech** [comment]
Thanks @erebion. Will update that soon!

**Comment by scouech** [comment]
@erebion just to let you know, the next release includes this. Closing the ticket. Cheers
