### ISSUE TITLE
Improve routing

### ISSUE THREAD

**Issue by michaelcspeed** [meditohq/medito-app#304]
`lib/utils/navigation_extra.dart`

We have a usecase where we maybe have folders within folders within folders. Each folder can contain sessions, folders, links to websites, text pages or links to videos. In previous versions of GoRouter you could not dynamically build routes, so the current implementation has a tree structure hardcoded with all these possibilities. It would be good if we didn't need to do that, apparently the newer versions of GoRouter can support dynamic routing.

**Comment by akhilk2802** [comment]
can i take this issue ?
