### ISSUE TITLE
[Screen] Player

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#307]
**Figma:**
[https://www.figma.com/file/E9k4sKjlBDUREveJbUtf4A/Untitled?node-id=201%3A131&t=DayARbWjklasiZ56-1
](https://www.figma.com/file/E9k4sKjlBDUREveJbUtf4A/Untitled?node-id=201%3A131&t=DayARbWjklasiZ56-1
)
**Description:**
— You will find on figma (under player page) the new player.
— Please check the comments for behavior etc.

**Endpoint:**
Data should be available when calling the session via `sessions/:id`

**Missing:**
_Will be coming soon, shouldn’t prevent implementation_
— The download dialog (when a session is being downloaded)
— The background sound bottom sheet (with the sound options)
Let me know if something is unclear or if you think it could be done differently

**Comment by osamaasifoak** [comment]
- [x] Migrating audio player to the riverport
- [x] Player UI from scratch
- [x] Audio positions indicator and audio speed handler
- [x] Custom network widget for cover URLs
