### ISSUE TITLE
[BUG] Text message tone stops session playing 

### ISSUE THREAD

**Issue by AzimLalan** [meditohq/medito-app#309]
We have received the below feedback from one of the users

"Every time I get a Text message while I’m meditating to a downloaded meditation, Siri Reads out my text message and then the meditation stops after that."

Version: 2.0.47
Device: {device_model: iPhone14,2, device_os: Darwin, device_platform: iOS}
Build Number: 20047
ReleaseMode: true, id:a2558dc1-9fcc-4ae4-9fee-321689c21d02 ----

**Comment by michaelcspeed** [comment]
I feel like this could be avoided by putting your phone in Do Not Disturb mode, so not a high priority for now.
