### ISSUE TITLE
Lock screen player shows Medito still playing after meditation

### ISSUE THREAD

**Issue by lambdakilo** [meditohq/medito-app#310]
**Describe the bug**
Lock scren player shows Medito is still playing after mediation has already ended and the user has left the application

**To Reproduce**
1. Complete one session from a course
2. Exit from the Medito app to the home screen
3. Slide the notification area from the top
4. See Medito session still "playing"

**Expected behavior**
I expected the application not be in any progress anymore in the notification center

**Screenshots**
![IMG_0421](https://user-images.githubusercontent.com/31825085/216373536-d8173985-bafe-4cee-89a7-4a6c1f3a7ce2.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 -  OS: iOS16.3
 - Version: 2.0.47

**Comment by scouech** [comment]
Fixed in the next release
