### ISSUE TITLE
[BUG] High battery use when idle after audio playback finished.

### ISSUE THREAD

**Issue by af7567** [meditohq/medito-app#322]
**Describe the bug**
I noticed that if I start a meditation or sleep story playing and go to sleep, then my phone battery is quite a bit lower when I wake up. It seems like the app has been busy all night long even though the playback finished after 15 minutes. 

In the screenshot it shows Medito was busy for 5 hours 13 mins, but the sleep meditation I started during the night was only about 20 minutes long. 

5 hours would be about the amount of time from when I started playback to when I woke up and closed the app / media notification.

**To Reproduce**
1. Start a sleep story
2. Press power button to turn off the screen and put the phone face down
3. Leave it for a few hours and check battery usage.

**Expected behavior**
When playback has finished the app should be idle.

**Screenshots**
![Screenshot_20230224-113932](https://user-images.githubusercontent.com/12093847/221172786-07922840-95f1-461b-b314-568caea21276.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: Android 12
 - Version: 2.0.48

**Additional context**
Maybe related to the problem where the media playback notification won't go away.

**Comment by OkyDooky** [comment]
I emailed them about this issue about a year ago or so, before I knew the app was alread open source.
I'm glad you opened a formal issue, so this could be tracked. Because, you are not the only one. I make sure to open the app settings before opening the app, so that it is easier to switch to it and hit "force stop" when the sleep meditation ends. Otherwise, I have the same result as you described.

**Comment by scouech** [comment]
Hi @af7567 @OkyDooky , in the next few weeks we will be releasing a brand new version of the app. It should fix the issue.
Thank you for reporting it. 
I will close the ticket for now. If you spot the problem again in the future feel free to open a new issue. 

Cheers
