### ISSUE TITLE
[Feature Request] Yoga Nidra

### ISSUE THREAD

**Issue by krillin666** [meditohq/medito-app#324]
Hi !

First of, this app has been helping me for more than 2 years now, and I'm very grateful to all who contributed to it.

I wanted to ask if it's possible, or you ever considered, to add Yoga Nidra protocols to the app ? Maybe in the sleep section ?

Thank you!

**Comment by michaelcspeed** [comment]
I have passed your feedback on to the content team - let's keep github as a place to talk about the codebase :)
