### ISSUE TITLE
Feature to show the next meditation on the top of the main app page

### ISSUE THREAD

**Issue by noahtf13** [meditohq/medito-app#326]
It would be great to be able to have a play button at the top of the page for the next meditation. For example, if you are on the 30 Day Meditation Challenge pack, and yesterday you did "Day 6", then "Day 7" would be suggested at the top of the app.

**Comment by Spyy004** [comment]
Can someone elaborate more on this, like the exact screen where this is needed and if no one is working can someone please assign me this?

**Comment by noahtf13** [comment]
I'd say that the initial/home screen would be great, I put red lines for two different spots where I think it could go.

![unnamed (3)](https://user-images.githubusercontent.com/76792111/228377941-8505d537-a8e7-431b-825f-89b2a96b29a9.jpg)

**Comment by michaelcspeed** [comment]
This is definitely needed but the homescreen is in the process of being redesigned, and currently the backend cannot tell you what the next session you should listen to is, because there's no endpoint for that.

**Comment by scouech** [comment]
@noahtf13 @Spyy004 
Working on it :)
