### ISSUE TITLE
Wiki instructions out of date

### ISSUE THREAD

**Issue by lambdakilo** [meditohq/medito-app#339]
![image](https://user-images.githubusercontent.com/31825085/228950344-2a39cb5c-a811-48af-904d-42def5c9642b.png)
For example there isn't #dev channel on Slack anymore.

**Comment by lightspeed1** [comment]
yeah slack link is broken, where else can I get an api key?

**Comment by lambdakilo** [comment]
@lightspeed1 I think you have to apply for a volunteer to get the API key from the slack.

**Comment by scouech** [comment]
@akirataguchi115 @lightspeed1
Part of the new app version (coming in the next few weeks) we decided to remove the github wiki. 
The API documentation and API key are for now available on request, and we will be writing new documentation for the app repo itself before the end of the year. So more coming soon! :)
