### ISSUE TITLE
Please allow disabling the streak counter

### ISSUE THREAD

**Issue by erebion** [meditohq/medito-app#350]
Please allow disabling the streak counter. It causes me stress seeing that there is still one thing to do today. I guess I'm not the only person streaks do not work at all for.

**Comment by scouech** [comment]
Hi @erebion.
The next version (coming in the next few weeks) will have optional user accounts. 
If you do not log in, the stats will not be displayed.
In the future we will implement the option to deactivate the stats even when signed in, but in the meantime we consider your suggestion taken into account. 

Cheers!
