### ISSUE TITLE
Change app icon

### ISSUE THREAD

**Issue by icejuice-enjoyer** [meditohq/medito-app#351]
Adding support would help better integrate the app icon in launchers on Android 13+ devices.

https://developer.android.com/about/versions/13/features#themed-app-icons
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

**Comment by scouech** [comment]
Thanks @icejuice-enjoyer .
I think @michaelcspeed has already changed the project to use Android 13 adaptive icons. 
Part of this, we are changing the logo itself and the color of it. You can find the assets in the ZIP file attached. 
@osamaasifoak Would you mind changing it for both iOS and Android please? :) Cheers


[medito-logo-may-2023.zip](https://github.com/meditohq/medito-app/files/11432261/medito-logo-may-2023.zip)

**Comment by scouech** [comment]
FYI: Adaptive icon was done part of #289 - so what we need to do now is change the actual logo using what's in the zip file.

**Comment by osamaasifoak** [comment]
30 ~ 40 minutes

**Comment by scouech** [comment]
perfect! cheers
