### ISSUE TITLE
Bottom sheet: Menu

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#352]
- Open by tapping 3 dots in top bar
- [Design here](https://www.figma.com/file/E9k4sKjlBDUREveJbUtf4A/Untitled?type=design&node-id=1190%3A9038&t=5PddAzB8lXBCnTDI-1)
- Icons should be app assets, the json will have an icon name like ic_help, when the name is ic_help, the app should display the ic_help icon stored as an app asset

**Comment by michaelcspeed** [comment]
I think this is clear enough? @osamaasifoak lemme know if anything is unclear

**Comment by osamaasifoak** [comment]
Yep! Thanks for the explanation

**Comment by osamaasifoak** [comment]
Completed
