### ISSUE TITLE
Bottom sheet: Status

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#353]
- Opens by holding 3 seconds on logo in top bar
- [Design here](https://www.figma.com/file/E9k4sKjlBDUREveJbUtf4A/Untitled?type=design&node-id=1213%3A9193&t=tzljkcHr9H2fDhcm-1)
- All data comes from backend
- Share button should open native share feature (see figma comments)

**Comment by michaelcspeed** [comment]
I would say just use a long-press, rather than a 3s hold

**Comment by scouech** [comment]
moved it to a new ticket #366
