### ISSUE TITLE
Add event tracking

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#362]
We have a new events endpoint ( POST /events)

You can find the full postman collection here:
[https://medito.postman.co/workspace/b22b5a3d-4f45-4545-9e0b-5d3d24353fe2/folder/2129110-4b94fd25-87ad-44e3-835d-1a371d5c68c2?ctx=documentation](https://medito.postman.co/workspace/b22b5a3d-4f45-4545-9e0b-5d3d24353fe2/folder/2129110-4b94fd25-87ad-44e3-835d-1a371d5c68c2?ctx=documentation)

The documentation is available on Postman for each event type.

Here are the following event types:

`appOpened` - when the app is opened

`audioStarted` - when a user starts an audio

`audioCompleted` - when an audio file finishes (used for streak)

`backgroundSoundSelected` - when a bg sound is manually selected

`folderViewed` - when a folder is viewed (when GET /folders/{id} is called)

`meditationViewed` - when a meditation is viewed (when GET /meditations/{id} is called}

`chipTapped` - when a chip is tapped on the home screen

`menuItemTapped` - when a menu item (retrieved via GET /home) is tapped

`statsTapped` - when the stats icon is tapped in the top bar on the homescreen (retrieved via GET /home - will be added to /home shortly).

**Comment by osamaasifoak** [comment]
14 ~ 20 hrs
