### ISSUE TITLE
Debug bottom sheet

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#366]
We’ve renamed the status bottom sheet to debug. This debug bottom sheet is now accessible by a long press on the Medito logo on the homescreen.

🔗 You can check out the new design preview on Figma here:
[https://www.figma.com/file/E9k4sKjlBDUREveJbUtf4A/Untitled?type=design&node-id=1213%3A9193&t=usjulXLajZDxhqNO-1](https://www.figma.com/file/E9k4sKjlBDUREveJbUtf4A/Untitled?type=design&node-id=1213%3A9193&t=usjulXLajZDxhqNO-1)

💻 The new `GET /me` endpoint is now live.
This endpoint will return the user’s remote info such as `id` and `email`. It’s documented in the Postman workspace:
[https://medito.postman.co/workspace/Medito~b22b5a3d-4f45-4545-9e0b-5d3d24353fe2/request/2129110-5272bd09-f9d7-48b7-906f-0f65f3f54d64?ctx=documentation](https://medito.postman.co/workspace/Medito~b22b5a3d-4f45-4545-9e0b-5d3d24353fe2/request/2129110-5272bd09-f9d7-48b7-906f-0f65f3f54d64?ctx=documentation)

❗️Remember, this debug sheet should also contain device specific information such as `appVersion`, `deviceModel`, `deviceOs`, `devicePlatform`, and `buildNumber`. This information isn’t returned by the endpoint but should be accessed from the device itself.

**Comment by osamaasifoak** [comment]
10 ~ 14 hrs

**Comment by scouech** [comment]
Moving that back to todo, only because of the share button. 

1. Open the debug sheet
2. Tap on share
3. It opens the default share dialog with a screenshot of the debug sheet. 

It's my fault, I did not explain well. 

1. The share button should be open the default email client
2. The email address should be `hello@meditofoundation.org`
3. The email subject should be `Bug report`
4. The email content should be like that:

--- Debug info ---
{all content from bottom sheet here, one item per line}
--- Write below this line ---

**Comment by osamaasifoak** [comment]
Added

**Comment by scouech** [comment]
@osamaasifoak could we make sure the debug body is starting with
--- Debug info ---
followed by the info
and then followed by 
--- Write below this line ---


Cheers

**Comment by osamaasifoak** [comment]
Fixed

**Comment by scouech** [comment]
see #440
