### ISSUE TITLE
Downloads don't work on iOS

### ISSUE THREAD

**Issue by michaelcspeed** [meditohq/medito-app#37]
Downloads don't work on iOS - this might be due to the `getApplicationSupportDirectory()` method of the `path_provider` package. 

See `lib/audioplayer/download_class.dart`

This also means that background audio is not possible on iOS (because the current implementation downloads the file as soon as you choose it in the `session_options_screen`)

**Comment by mohit92** [comment]
PR for the fix: https://github.com/meditohq/medito-app/pull/85
