### ISSUE TITLE
Announcement Feature

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#372]
## Summary

We've introduced a new feature and event logging to our API. The home screen now includes an optional announcement, and we've added a new event type `announcementCtaTapped` for logging when a call-to-action (CTA) in an announcement is tapped.

## Tasks

1. **Home Screen Announcement**: Update the home screen to handle the optional `announcement` property in the response from the `GET /home` endpoint. This property is an object that represents a special announcement or message to the user. It has properties like `id`, `icon`, `text`, `ctaTitle`, `ctaType`, `ctaPath`, `colorBackground`, and `colorText`. Note that `icon`, `ctaTitle`, `ctaType`, and `ctaPath` are optional and will only be present under certain conditions.

2. **Event Logging**: Implement event logging for the new `announcementCtaTapped` event. This event is triggered when a user taps on a CTA in an announcement. The event `name` is `announcementCtaTapped` and the body parameters include `name` and `payload`. The `payload` object contains `announcementId` and `ctaTitle`.

## Acceptance Criteria

- [x]  The home screen should correctly display the announcement when present in the response from the `GET /home` endpoint.

- [x] Tapping on a CTA in an announcement should trigger the `announcementCtaTapped` event and send the correct data to the `POST /events` endpoint.

Please let me know if you have any questions or need further clarification.

## Figma

- See the 3 types of announcement layouts (with icon + CTA + dismiss // with no icon // with no CTA)
[https://www.figma.com/file/E9k4sKjlBDUREveJbUtf4A/Untitled?type=design&node-id=1498%3A10392&t=fLQHt5cFowCEDMpH-1](https://www.figma.com/file/E9k4sKjlBDUREveJbUtf4A/Untitled?type=design&node-id=1498%3A10392&t=fLQHt5cFowCEDMpH-1)

- How the announcement fits on the home screen
[https://www.figma.com/file/E9k4sKjlBDUREveJbUtf4A/Untitled?type=design&node-id=1475%3A11217&t=fLQHt5cFowCEDMpH-1](https://www.figma.com/file/E9k4sKjlBDUREveJbUtf4A/Untitled?type=design&node-id=1475%3A11217&t=fLQHt5cFowCEDMpH-1)

**Comment by osamaasifoak** [comment]
16 ~ 20 hrs

**Comment by scouech** [comment]
@osamaasifoak we have a little issue here. 
If you tap on the dismiss button and/or the CTA, it sometimes send multiple events to the backend via the POST /events endpoint. 

It seems to make multiple POST calls basically

![Image](https://github.com/meditohq/medito-app/assets/26603052/aa676101-7d18-40fb-9d85-71dc67e86063)

**Comment by osamaasifoak** [comment]
Fixed!!

**Comment by scouech** [comment]
Perfect! Cheers
