### ISSUE TITLE
Support more languages.

### ISSUE THREAD

**Issue by JiagengDing** [meditohq/medito-app#399]
I want to submit a PR to add support for Chinese.  
But I didn't find a file that can support translation.

**Comment by quazar-omega** [comment]
I believe this is where the strings reside https://github.com/meditohq/medito-app/blob/develop/lib/constants/strings/string_constants.dart but I don't know if the app has any localization library implemented yet.  
I'd be glad to add support for Italian myself

Edit: it's planned as per https://github.com/meditohq/medito-app/issues/305

**Comment by scouech** [comment]
Most of the translation will be done from the backend side. We still have some hardcoded stuff in the new app (v3) but it will be moved to the backend too. I will close this for now as it only relates to the backend and this is issues for the app only. Thanks everyone!

**Comment by quazar-omega** [comment]
Got it!  
Can you update us here as well with the link to the site where we can contribute translations when that's ready?
