### ISSUE TITLE
Announcement animation

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#403]
Can we animate the announcement when it appears and when it is dismissed?  To slide in . slide out

**Comment by osamaasifoak** [comment]
Animation added

**Comment by scouech** [comment]
The current animation behavior for the announcement isn't aligning with what we're aiming for. Right now, the announcement becomes invisible before sliding out, which isn't the intended effect. Instead, it should remain visible while sliding out.

Similarly, the slide-in animation doesn't feel natural. It seems to scale up and originate from the center, rather than simply sliding in from the top as expected.

Lastly, the refresh animation shows a residual purple background (or the respective background color) after the announcement has been dismissed and upon refresh, which is not intended.

I'd like the announcement to smoothly slide in from the top when it appears and slide out while still visible when dismissed. Could you please adjust the current behavior to meet these expectations?

Cheers

**Comment by scouech** [comment]
@osamaasifoak it seems to refresh the homescreen when I tap on dismiss, also, if there is a new announcement and I pull down to refresh it doesnt show. I have to reopen the app. Could we fix that? Cheers

**Comment by osamaasifoak** [comment]
I have added the above change lmk how can I test this?
