### ISSUE TITLE
Share sheet update

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#405]
When tapping on Stats > Share, it opens the native share dialog for the stats, that’s great.

- It generates an image, it’s very very low quality, can we improve that? What are the current settings? Let me know so that we can agree on a size

- Can we change the share text to: 

`Discover calmness for FREE with #Medito 🧘‍♂️ I've found my inner peace; now it's your turn! Join me on this mindful journey and start exploring today 💜 Download medito.app #Calm #Meditation #Headspace`

**Comment by osamaasifoak** [comment]
Hi @scouech, I'm now using the device pixel ratio to improve image quality. Please let me know if it still needs adjustments.

**Comment by scouech** [comment]
Perfect! thanks!
