### ISSUE TITLE
Refresh behavior

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#406]
For the folder and meditation screens, can we change that behavior so that you can pull down to refresh but it doesnt move the description?

(See Slack here https://meditofoundation.slack.com/archives/C05JELT0AGH/p1691666509731209?thread_ts=1690197582.376749&cid=C05JELT0AGH)

Also, can we improve the refresh behavior for the background sound screen?

**Comment by osamaasifoak** [comment]
I have changed the behavior you will able to see the change in new build

**Comment by scouech** [comment]
@osamaasifoak there is no more refresh for the background sounds?

**Comment by osamaasifoak** [comment]
https://github.com/meditohq/medito-app/assets/49792938/b6474473-b000-4338-8270-26ff60f1d539

**Comment by scouech** [comment]
@osamaasifoak I still don't see the refresh behaviour working for short screen
(ie students > moving away from home)

**Comment by osamaasifoak** [comment]
https://github.com/meditohq/medito-app/assets/49792938/1d9962de-8f9f-4534-8773-36c766bfb7bf

**Comment by scouech** [comment]
great! cheers
