### ISSUE TITLE
Glitch with play/pause button when opening app

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#409]
If you kill the app, and reopen it, look at the mini player at the bottom, the play/pause icon changes state automatically. It should always be "stopped" at this time, as the app is just opened.

See on Slack here: https://meditofoundation.slack.com/archives/C05JELT0AGH/p1691667607030579?thread_ts=1690197523.243179&cid=C05JELT0AGH

**Comment by osamaasifoak** [comment]
Fixed!!

**Comment by scouech** [comment]
Thank you!
