### ISSUE TITLE
Event folderViewed is not fired

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#414]
When opening a folder, the event /events eventName folderViewed is not fired

See documentation here:
https://medito.postman.co/workspace/Medito~b22b5a3d-4f45-4545-9e0b-5d3d24353fe2/request/2129110-f0ae5655-7916-419a-b049-3814acd90ee2?ctx=documentation

**Comment by osamaasifoak** [comment]
Fixed!!
