### ISSUE TITLE
Can't go back to homescreen after opening author webview

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#420]
1. Go to the third row on the home screen (UCLA)
2. Tap on the first item (Meditacion en espanol)
3. Start playing one
4. Tap on the author on the big player (UCLA)
5. It opens the webview (all good)
6. Close the webview by tapping the close icon
7. Close the meditation screen by tapping the close icon
8. Close the folder screen :large_orange_circle:  It doesn’t close, and then you are stuck.

**Comment by osamaasifoak** [comment]
Fixed

**Comment by scouech** [comment]
Perfect.
