### ISSUE TITLE
Audio stopped playing on navigate back

### ISSUE THREAD

**Issue by shatanikmahanty** [meditohq/medito-app#422]
**Describe the bug**
Audio stops when navigating back from the playing screen

**To Reproduce**
1. Go to any of the meditation module
2. Click on Begin
3. Use Android navigation to go back to the previous screen 
4. Audio will stop playing

**Expected behavior**
In most apps for eg. Spotify, the audio keeps on playing, this allows the user to browse through the app if they want

**Smartphone (please complete the following information):**
 - Device: Realme GT Master Edition
 - OS: Android 13
 - Version: 2.0.48 
 Device: {device_model: RMX3360, device_os: 13, device_platform: android} 
 Build Number: 20048 
 ReleaseMode: true 0cc15727-ea83-40d3-94a6-55193c27f25b

**Comment by scouech** [comment]
Hi @shatanikmahanty thanks for posting about this. The new version will include an "always on screen" player.
We are expecting to rollout by stages from beginning of September. Keep an eye on it :)
I will close this ticket.
