### ISSUE TITLE
Debug sheet

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#424]
1. I think you already reduced the time to display the debug sheet, but it still doesn't work properly on my end. It seems I have to really press hard to get it to show? Can we change the bahaviour?

2. Could we call the endpoint before displaying the bottom sheet? It seems we are opening the bottom sheet and then calling the endpoint.

**Comment by osamaasifoak** [comment]
1. Yes, I can reduce the time to 500 milliseconds

2. No, I'm not calling an API after opening a bottom sheet

**Comment by scouech** [comment]
oh odd about 2, it looks like it's loading after the sheet opens. You can see the bottom sheet opening, and then there is a loading spinner @osamaasifoak

**Comment by osamaasifoak** [comment]
Ohh yes, if you open the bottom sheet the first time, it will call the API, but the second time it will get the data from the cache.

**Comment by scouech** [comment]
ok, so then could we do the call first before opening the sheet? 🤓  Cheers

**Comment by scouech** [comment]
and when is that cache refreshed? when the app is reopened from killed? Let's not cache it, otherwise we will have cases when it will not be up to date and it's gonna be a bit messy @osamaasifoak

**Comment by osamaasifoak** [comment]
Yes @scouech, I can call the API before opening the bottom sheet.

**Comment by osamaasifoak** [comment]
No, it's not like that actually, I'm using ref.keepalive to preserve the provider state. Let me provide you with some information regarding this.

https://riverpod.dev/docs/concepts/modifiers/auto_dispose#refkeepalive

**Comment by scouech** [comment]
Great! Thanks!
