### ISSUE TITLE
Use local fonts rather than Google Fonts

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#427]
In light of GDPR concerns about Google Fonts possibly logging IP addresses and other user information, I'd like us to make some changes:

**Local Fonts Usage:** Since we're already using 'Clash Display' locally, let's also incorporate 'DM Mono' and 'DM Sans' as local fonts. I've uploaded the ZIP file containing these fonts to Slack [See here](https://meditofoundation.slack.com/archives/C04LD4ZQ91N/p1692712421114089?thread_ts=1692712377.675309&cid=C04LD4ZQ91N)

**Font Weights:** The ZIP file includes the font weights we currently use in the app, plus a few extras for potential future needs.

**Google Fonts Removal:** Once the transition to local fonts is complete, ensure that all references and dependencies to Google Fonts are removed from the project.

Thank you :)

**Comment by osamaasifoak** [comment]
Local fonts added!!
