### ISSUE TITLE
Animate row items

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#431]
Could we animate the row items on tap? 
[Here is a link to Slack](https://meditofoundation.slack.com/archives/C04LD4ZQ91N/p1692819886724819) of a recording showing what I mean.
The animation "shrinks" the item on tap, leading to its destination. 

Cheers!

**Comment by osamaasifoak** [comment]
Added!!

**Comment by scouech** [comment]
It should scale the entire view, including the text, not just the background. Because the text otherwise is moving and the items in the row too (the items should not move, it should just shrink the tapped item.)

**Comment by scouech** [comment]
@osamaasifoak could we remove it? it still shows on the testflight build. You can also remove the related library. Cheers
