### ISSUE TITLE
handle expired session

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#436]

**Comment by scouech** [comment]
@osamaasifoak could you add more details to this ticket please? What is it about etc? Cheers

**Comment by scouech** [comment]
@osamaasifoak see above

**Comment by osamaasifoak** [comment]
Hi @scouech, I noticed that if we don't open an app for a few days, our token expires and the user can't use the app. To fix this, I added an error check to see if the token has expired. If it has, I'll take the user to the splash screen and repeat the process.
