### ISSUE TITLE
[BUG] Progress bar stops working properly after first swipe

### ISSUE THREAD

**Issue by akamofu** [meditohq/medito-app#438]
Every time i open a session, if i change the time position once it all works well: The cyan circle follows my touch, as well as the progress bar at its left does. But if i try to change the time position for a second time after opening the session, the circle only gets to the position my finger is when i take it out of the screen, remaining *stationary* while i swipe. There is no problem with the numeric timer, just with the graphical elements (circle and bar) that represent its progress. Kinda looks like #259, but it's a different problem. 
The expected behavior was to have the circle and the bar always following my touch, while still changing the time position only when i take my finger out.
I use Medito in an Android 10 system, if this helps.

**Comment by scouech** [comment]
Hey @sadparadise , this issue is fixed in the new release. We have been a little bit delayed but it should be rolling out in 2 weeks. I will close this for now. Thanks for your help!
