### ISSUE TITLE
Background Color shouldn't take announcement color

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#444]
The color of the top of the announcement should take the announcement color background. Which is correct at the moment. However it seems like you used the background color announcement as a background color for the entire screen. The color should be used only for the top of the announcement. The rest of the screen color should not change. 

See Slack link here:
[https://meditofoundation.slack.com/archives/C05JELT0AGH/p1693924959557589](https://meditofoundation.slack.com/archives/C05JELT0AGH/p1693924959557589)

**Comment by osamaasifoak** [comment]
https://github.com/meditohq/medito-app/assets/49792938/3519eae3-ee28-41b5-9d54-1bcd7f398346

**Comment by scouech** [comment]
Thats great! Thanks Osama :)
