### ISSUE TITLE
Log minutes when timer is stopped before finishing

### ISSUE THREAD

**Issue by m-oxu** [meditohq/medito-app#450]
I thinks this feature is good to have. In a lot of occasions, I sit to meditate for 30 minutes, but something happened that I should get up and do something (life can't be controlled). The timer will not log how much I already meditated without me finishing the predefined time that I set.

I think it would be good at least to log every 5 minutes of meditation. So, if I meditate 23 minutes when set 30 minutes, it will log 20 minutes, not 23 minutes.

**Comment by michaelcspeed** [comment]
This would be nice but we have no plans to do it right now. It's currently calculated based on the length of the session, so this would take quite some rework. Maybe we will pick it up in the future but I will close it for now
