### ISSUE TITLE
Fix Retry Mechanism

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#487]
When the an error is thrown during initialisation, the app tries to retry but an error occurs.

To reproduce this, throw an error in `appInitializationProvider` (e.g. alter the INIT_TOKEN and rerun the app)

` Unhandled Exception: 'package:riverpod/src/framework/element.dart': Failed assertion: line 476 pos 11: '_debugCurrentlyBuildingElement == null ||
              _debugCurrentlyBuildingElement == this': Providers are not allowed to modify other providers during their initialization.
`

Please also write unit tests to test these scenarios.

**Comment by scouech** [comment]
@osamaasifoak that has not been done I think?

**Comment by osamaasifoak** [comment]
Hey @scouech, the task has been completed thanks.
