### ISSUE TITLE
Background audio is too loud

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#5]
A few people have reported that the background audio volume is too high when starting a meditation.

What we should be doing is to probably have it at 60% by default like it was before adding the background audio volume control.

**Comment by botsonthego** [comment]
not only that when using background audios at 55% to 27% the audio come out strage as if its butting in and out

**Comment by scouech** [comment]
@botsonthego sorry but I'm not sure I understand. Do you mean that even when the volume is at 27% it is still very loud? Cheers

**Comment by michaelcspeed** [comment]
fixed in latest release
