### ISSUE TITLE
Announcements should be optional

### ISSUE THREAD

**Issue by erebion** [meditohq/medito-app#537]
**Describe the bug**
The app contains announcement banners which currently cannot be disabled.

**To Reproduce**
1. Open app for meditation
2. Banner tells about a new Youtube video occasionally

**Expected behavior**
The notifications should be optional.

**Additional context**
For meditation and/or help with sleep it is not necessary to learn about a new video on Youtube, this might even be counter-productive.

**Proposed solution**
Make this optional by letting the user decide to receive notifications or not using a setting for whether this should be on or off. The first time the app gets opened, this could be part of the onboarding flow.

**Comment by michaelcspeed** [comment]
We have no plans to make them optional at the moment. We use the announcements to alert users about outages and stuff so I don't think we should.

**Comment by erebion** [comment]
Yeah, not everyone wants to get alerted about stuff.
