### ISSUE TITLE
[GH Actions] build pipeline

### ISSUE THREAD

**Issue by ilyamochalov** [meditohq/medito-app#55]
We need a build pipeline for both iOS and Android + post to the play store and app store

**Comment by scouech** [comment]
would be ideal!

**Comment by porfirioribeiro** [comment]
I don't know how easy it is to implement in GH Actions
We use https://codemagic.io and it's very nice. You can build and sign for Android, iOS, Web, Desktop...
I guess you can go with the free plan, it should be more than enough.
And if it isn't, you can talk to them and they would probably increase your build minutes.

By the way, nice work on this app, i honestly appreciate it :100:

**Comment by michaelcspeed** [comment]
@porfirioribeiro I was using CodeMagic but the free plan doesn't allow for more than one user. I emailed them multiple times to ask if they do a non-profit discount and they never replied. Hence the switch to github, if possible! :)

**Comment by porfirioribeiro** [comment]
@michaelcspeed ohh that sucks. Good luck implementing with GH actions :)

**Comment by qtdzz** [comment]
I don't have prior experience with [FastLane](https://docs.fastlane.tools/) but from what I read, it is very cool. It can deploy to beta/production for both iOS and Android. Some references for integration with flutter:
- https://flutter.dev/docs/deployment/cd#integrating-fastlane-with-existing-workflows
- https://medium.com/flutter-community/deploying-flutter-ios-apps-with-fastlane-and-github-actions-2e87465e056e
- https://joshuamdeguzman.com/continuous-delivery-for-flutter-using-fastlane-and-github-actions-pt-2-android/
- https://joshuamdeguzman.com/continuous-delivery-for-flutter-using-fastlane-and-github-actions-pt-3-ios/

I can give try it with my personal developer account and let you know the result.
