### ISSUE TITLE
Clear downloaded files / mp3 when first open

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#560]
When we get the transferStats, we clean the cache, but I don't think that's cleaning the downloaded files (mp3) from the previous version, is it? We should clear the local storage also. Can we do that if it's not already the case? 
Cheers

**Comment by scouech** [comment]
you might have to get the list of downloaded sessions (from the previous version) and clear them one by one, unless there is a way to delete everything from the cache / storage in one go?

**Comment by scouech** [comment]
@osamaasifoak could you let me know how it works? Cheers

**Comment by osamaasifoak** [comment]
Yeah sure, so, in the old app, we were saving the list of media items in local storage and the audio track file in the local directory. So, every time we open the app I check if the media items are present in the local storage in that case I'm running a loop that checks whether the audio file exists in the directory and deletes the file, and at last, I'm clearing the local storage.

**Comment by scouech** [comment]
thanks! what happens if you have the new app, download stuff and reopen the app next time? will it clear the new downloaded files too?

**Comment by osamaasifoak** [comment]
No, it will not clear the newly downloaded files
