### ISSUE TITLE
Add audio_session and allow other audio apps to play at the same time

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#575]
People have been asking if we could let Medito's audio continue if other apps play audio.
It seems it is possible with this
[https://pub.dev/packages/audio_session](https://pub.dev/packages/audio_session).

If audio on Medito is playing and I try to play audio on Spotify, Apple Music etc the audio on Medito should continue playing.

- [x] Investigate if it's possible with the library shared above
- [x] Implement solution: audio on Medito should continue playing if I play audio in another app.

**Comment by osamaasifoak** [comment]
https://meditofoundation.slack.com/archives/C05JELT0AGH/p1700491274204549
