### ISSUE TITLE
Only ask for notification permission once

### ISSUE THREAD

**Issue by michaelcspeed** [meditohq/medito-app#586]
Some users complain that they are getting the notification request screen multiple times. We could also get in trouble with the app stores if we ask too often

**Comment by scouech** [comment]
@osamaasifoak if a person does not allow notification, do they still get a FCM token? I can't remember. 
Could you let me know first please, and then if they don't, then let's hide the screen for now after 3 rejection. Is that ok? Cheers

**Comment by osamaasifoak** [comment]
When you open the app for the first time, I generate the FCM token. This is because some devices automatically allow notification permission, but on Android 13 or later versions and iOS devices, you won't receive notifications until you explicitly allow the permission.
