### ISSUE TITLE
Nothing to pop after welcome screen

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#597]
If you go through the join flow, once you have entered the OTP correctly, you arrive on the screen with `Thanks for being on this journey with us` however when you tap on `Close` it does not work. It says `There is nothing to pop` in the console

**Comment by osamaasifoak** [comment]
I checked the join flow from the track screen when opening the track for the first time and also from the player screen after completing the audio, I verified that it is working correctly.
