### ISSUE TITLE
End Screen

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#605]
We want to display an "end screen" after a track ends. 

### Design
You can find the design here:
https://www.figma.com/file/E9k4sKjlBDUREveJbUtf4A/Medito-2023?type=design&node-id=2495%3A1303&mode=design&t=3wCXmIYFpcr9WkCv-1

- [x] Top bar is material
- [x] Closing that screen should also close the player
- [x] The color of the `donationAskCard` text and background comes from the payload

### Payload
You can find the array called "`endScreen`" when getting a track ( `POST /tracks/{id}` )
In this array you will find two sub arrays. 
1. `feedbackCard` which contains the title and text for the card and the options
2. `donationAskCard` which contains the donation ask card title, text, cta info and style details

- [ ] The order of the cards is based on the order in which they come from in the payload
- [x] The `feedbackCard` always has the feedback options, they come from the payload
- [x] The `donationAskCard` style is based on the payload

#### feedbackCard
- [x] Tapping on a emoji should trigger `POST /events trackFeedback`.
https://medito.postman.co/workspace/Medito~b22b5a3d-4f45-4545-9e0b-5d3d24353fe2/request/2129110-20adfe0d-86fb-463d-a749-381b2fbc846e?ctx=documentation

- [x] It should replace the available choices by the text "Thanks for sharing".
- [x] You can't change your choice once you have selected one.

#### donationAskCard
- [x] Tapping on the CTA should trigger `POST /events ctaTapped`
https://medito.postman.co/workspace/Medito~b22b5a3d-4f45-4545-9e0b-5d3d24353fe2/request/2129110-41078d1e-0cd3-4364-b388-72460d7ba82f?ctx=documentation

**Comment by osamaasifoak** [comment]
6 - 8hrs

**Comment by scouech** [comment]
@osamaasifoak here is the link to the prototype (showcasing the feedback animation). 
If we can do something similar it would be great. No need to spend too much time on it.

https://www.figma.com/proto/E9k4sKjlBDUREveJbUtf4A/Medito-2023?type=design&node-id=2542-11893&t=1s4aBNpqNWy8KQoz-1&scaling=min-zoom&page-id=2324%3A10511&starting-point-node-id=2495%3A1303&mode=design


You can find the screen showing the `thank you ` next to the other screen on Figma
