### ISSUE TITLE
Pull down to refresh should also refresh images

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#606]
When pulling down to refresh on the home screen (or any other screen) it refreshes the payload, however it does not refresh the images. 
Could we investigate so that when pulling down to refresh, we also refresh the images? 

Cheers :)

**Comment by scouech** [comment]
@osamaasifoak if you can add the estimate please :)

**Comment by osamaasifoak** [comment]
I am not sure, why it is happening here are the rough estimates 3 ~ 4 hrs.

**Comment by scouech** [comment]
Fixed by adding version number to assets in the payload
