### ISSUE TITLE
Remove in-app webview

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#609]
Unfortunately we are getting too many issues with the in-app webview. It's impacting on a partnership and the only way around it is to open the links in the default web browser. 

The `url` type is already opening the links in the correct location (default web browser) so all we need to do is make sure `link` type also opens in the default web browser.

- [x] Make `link` open in same location as `url`
- [x] Make sure link and url open externally
- [x] Remove everything related to in-app webview

**Comment by scouech** [comment]
@osamaasifoak if you can add the estimate please :)

**Comment by osamaasifoak** [comment]
2~3 hrs
