### ISSUE TITLE
type 'Null' is not a subtype of type 'double'

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#619]
It happens on prod and staging (so you should be able to find the cause on staging). 

`type 'Null' is not a subtype of type 'double'
`

We are getting this error too many times. Could you look into it?

Cheers

https://medito-foundation.sentry.io/share/issue/65bd41cf33344a45aa56a06b36789f2e/

**Comment by scouech** [comment]
It might be that one endpoint returns null and we haven't made it nullable?

**Comment by osamaasifoak** [comment]
Let me check the sentry logs

**Comment by osamaasifoak** [comment]
2hrs
