### ISSUE TITLE
Home revamp

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#623]
Based on the (very) high number of feedback we have received, we are revamping the home screen. This will not only help regarding the feedback, but also allow us to allocate the quote, stats in a more prominent way and other media items we want to display. 

# Design
You can find the design in this new figma file:
https://www.figma.com/file/EjZtnDvYjrWKaYKRQpU2oq/Medito-2023-v2?type=design&node-id=2805%3A15569&mode=design&t=H0UrW3O32HTLur9v-1

# Endpoint
The home screen is now divided in multiple parts, each part has its own endpoint:
## Header
`GET /main/header`
Basically the top bar navigation. It has three elements:
1. Greeting
2. Announcement (same as we currently have)
3. Menu (same as we currently have)

- The announcement can be present, if dismissed it will not be in the payload
- Greeting can change based on the payload

## Shortcuts
`GET /main/shortcuts`
It's a section with shortcuts, similar to the chips we currently have
- People should be able to reorder them by drag/drop. It should be saved locally for now

## Quote
`GET /main/quote`
It shows a quote with text and an author. The author is below the text.

## Tiles: stats
`GET /main/stats`
For now we have two tiles:
1. A first tile, can be any sort of data but will always be the same format
a. An icon
b. A title
c. A subtitle
d. A color, for the icon color
The first tile should open the bottom sheet with the stats. The stats are in the payload under "allStats"

2. A second tile, can be any sort of data, always the same format (same as above)
There is nothing to open here.

**Comment by scouech** [comment]
⚠ @osamaasifoak do not remove the explore FAB button, we are keeping that. Also please keep for now the model for the rows. 
The /home endpoint and /stats endpoint is being discontinued. So only /main/... and main/stats are the one that should be used

**Comment by osamaasifoak** [comment]
16 - 20 hrs
