### ISSUE TITLE
You cannot add items while items are being added from addStream

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#627]
1. https://medito-foundation.sentry.io/issues/4614988061/?environment=production&project=4505821085106176&query=is%3Aunresolved+release.version%3A3.0.12&referrer=issue-stream&statsPeriod=14d&stream_index=0

It seems related to an await missing somewhere from what I was reading. But not sure. 

Cheers

**Comment by osamaasifoak** [comment]
1. https://medito-foundation.sentry.io/issues/4614988061/?environment=production&project=4505821085106176&query=is%3Aunresolved+release.version%3A3.0.12&referrer=issue-stream&statsPeriod=14d&stream_index=0
2. https://medito-foundation.sentry.io/issues/4614988061/events/b5ad21a459aa44fcb5f8166390a464ed/
3. https://medito-foundation.sentry.io/issues/4587547456/events/a89cc0f64b6747fe9f599c6d71def7cd/
4. https://medito-foundation.sentry.io/issues/4659156466/events/8f85f441aa184f539b7a2a4c14678f33/
