### ISSUE TITLE
Events: The request connection took longer than 0:00:30.000000. It was aborted.

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#628]
**Events endpoint**

`{error: DioException [connection timeout]: The request connection took longer than 0:00:30.000000. It was aborted., endpoint: events, response: null, serverMessage: The request connection took longer than 0:00:30.000000. It was aborted.}`

However the events endpoint doesn't need to await for a response, as it's a simple POST with no response needed. Maybe let's do it so that we need to wait for a response and keep trying till we get 200? 
What would be the best approach?

**Comment by scouech** [comment]
Would be good to know your thoughts @osamaasifoak @michaelcspeed

**Comment by michaelcspeed** [comment]
We app still waits for a response because it still expects a 200, to make sure that it was sent correctly.
How many of these are we getting? Could it be due to poor internet connection?

**Comment by osamaasifoak** [comment]
Yes, @michaelcspeed it's happening due to the bad internet connection. The error interceptor in the dio client provider logs all API exceptions. @scouech we are not waiting for event requests to be completed all these requests are working in the background.

**Comment by scouech** [comment]
@osamaasifoak it seems to also happen for the userToken generation
https://medito-foundation.sentry.io/issues/4529354305/events/af4d7d499f864d8eb3510f60e31b0fe3/
and a bunch of others. Are we sure it's only because of bad internet connection? It's a lot lot of event and users impacted. We are usre it's not an issue with DIO or the way it was implemented?

**Comment by osamaasifoak** [comment]
https://meditofoundation.slack.com/archives/C05JELT0AGH/p1703066718745729
