### ISSUE TITLE
Remove XXX meditators row from stats sheet

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#640]
As we have a card for the number of meditators on the new home screen, we don't need to display the number in the stats bottom sheet. 
Could we please remove it from the UI? It's the object in `allStats` It might still be in the response for now. 
Cheers

**Comment by osamaasifoak** [comment]
@scouech, I can add a check to remove the number of mediators, but it would be great if you remove it from the back end and it will automatically be removed from the UI.

**Comment by scouech** [comment]
Oh right ! So if I remove that line from the response it will be removed from the UI, with nothing to do on your end? Perfect, dont worry. No need to do anything on your end then

**Comment by osamaasifoak** [comment]
Correct!!
