### ISSUE TITLE
Will the Medito 3 build be available?

### ISSUE THREAD

**Issue by manoelpqueiroz** [meditohq/medito-app#642]
I have downloaded Medito through F-Droid (v2.0.48 through IzzyOnDroid repo) and since the message mentioning the shutdown of version 2 starting from December 19th, I would like to know if the release build will be available through GitHub or will we as users be responsible for building the APK from the source.

**Comment by scouech** [comment]
@manoelpqueiroz for now we don't offer an official APK. You can always use a website like APK Pure in the meantime.
https://apkpure.com/nl/medito-meditation-sleep/meditofoundation.medito/download

However it might not work if you don't have Google Play Services as explained here:
https://github.com/meditohq/medito-app/issues/581

**Comment by xusiai** [comment]
> for now we don't offer an official APK. You can always use a website like APK Pure in the meantime.

Why cease Github releases? If you do not want to bother with an official F-Droid release at least having Github actions provide an apk allowed for a trusted source.

I don't mean to sound rude - I love Medito and am thankful for its existence - but it seems a bit awkward to me for an open source application to recommend users turn to websites like apkpure which serve uncontrolled user-uploaded xapks which require their own adware-infested closed source storefront to install it.

**Comment by scouech** [comment]
@xusiai I agree, it's just a question of time at the moment, we haven't had a chance to fix the Github pipeline.

**Comment by 1Maxnet1** [comment]
> @xusiai I agree, it's just a question of time at the moment, we haven't had a chance to fix the Github pipeline.

Do you have any hints on what is broken in the GitHub pipeline? If I find some time, I would have a look and whether I can help with the fix.

**Comment by michaelcspeed** [comment]
Android pipeline fixed. Newest apk is on github :)

**Comment by manoelpqueiroz** [comment]
Thanks @michaelcspeed! Really appreciate what Medito has to offer, you did an amazing job with the latest version, keep up the good work!

**Comment by debnath-d** [comment]
@michaelcspeed I'm not able to see where the APK is. I can't see any new release.

**Comment by Sinestr0** [comment]
@michaelcspeed @scouech As I can check, the release section shows v2.0.48 as the latest released apk which was published on 21 Jul 2022. Kindly fix the issue and release latest apk on github. Thank you

**Comment by LinuxinaBit** [comment]
> Android pipeline fixed. Newest apk is on github :)

This appears to be flat out incorrect.

**Comment by ChrisWin22** [comment]
> This appears to be flat out incorrect.

Not entirely. The apk is on github. You can find it in the `Deploy to Play Store` action in the `Artifacts` section. It looks like something just went wrong and it never got added to the releases.
