### ISSUE TITLE
Change navigation for bottom bar

### ISSUE THREAD

**Issue by scouech** [meditohq/medito-app#650]
- [x] Add material 3 bottom bar with home and explore
- [x] Remove FAB
- [x] Remove auto opening of keyboard for search bar
- [x] Move explore (search screen) to home page and navigate with bottom bar
- [x] Rename search files for explore
- [x] Add swipe gesture to move between home and explore

**Comment by hrithikm2** [comment]
Hi @scouech, @osamaasifoak. I can take this up 👍
