### ISSUE TITLE
[BUG] Announcement action for rating 5 stars does not respond to tap events.

### ISSUE THREAD

**Issue by hrithikm2** [meditohq/medito-app#657]
**Describe the bug**
At the home page of the app, there is an announcement banner that tells user to contribute by providing 5 stars to the app, However, this does not seem to work as nothing happens on tapping the "Give 5 stars" button.

**To Reproduce**

1. Go to 'home'
2. Wait for the banner to rate app appear.
3. If it does, tap on "Give 5 stars" button.
4. Nothing happens.

**Expected behavior**
After tapping on the button, ideally, this should redirect to Play store/AppStore page of the app depending on the OS.

**Screenshots**
![photo_2023-12-28 12 14 12](https://github.com/meditohq/medito-app/assets/72312835/2d96ee7b-de01-4b8b-b801-b048c1757d72)

**Smartphone (please complete the following information):**

- Device: Samsung Note 10 Lite(SM-N770F)
- OS: Android 13
- Version : 3.0.13
- Platform - Android

**Additional context**
I've checked the code, this seems to be an issue from the Firebase or the backend configuration. The cta action or path once assigned to the button should work.

**Comment by scouech** [comment]
hmm that's really weird. It works on iPhone, Google Pixel and other Android phones. It's not an issue with the backend. 
Could you update the app to the latest version? The screenshot shown above is not the latest one. Does it work with the new version? @hrithikm2 

Cheers

**Comment by hrithikm2** [comment]
Yes, the problem persisted even after I updated the app.  I posted the screenshot of a previous version, and realised that thing, quickly updated and checked again. It didn't work. 
However, now the **30 day challenge** action is working as expected. 
So problem might be related to something that my device does not support.  I'll keep testing the actions a bit more and keep note of issues if any.
