### ISSUE TITLE
[BUG] App stuck with black screen

### ISSUE THREAD

**Issue by Studiedlist** [meditohq/medito-app#663]
**Describe the bug**
I've downloaded and installed the app via ApkPure on my Huawei P40 lite. When I start the app, screen goes black and nothing happens

**To Reproduce**

1. Download and install the app 
2. Start it
3. Screen goes black

**Smartphone (please complete the following information):**

- Device: Huawei P40 lite
- OS: EMUI 12.0.0 (Android)
- Version: 3.0.13

**Comment by jowodo** [comment]
Same goes for iOS 17.2.1 on iPhone 15pro with medito 3.0.13 without internet connection.

**Comment by jowodo** [comment]
Probably related to #581

**Comment by michaelcspeed** [comment]
Possibly yes @jowodo 

If it set 

```
 var isPlayServices = await checkGooglePlayServices();
  if (isPlayServices) {
    await Firebase.initializeApp();
    await registerNotification();
  }
```

to 

```
 var isPlayServices = await checkGooglePlayServices();
  if (false) {
    await Firebase.initializeApp();
    await registerNotification();
  }
```
AND go on airplane mode, then I get stuck on the splash screen (not a black screen though)

It doesn't explain @Studiedlist's problem either. When I get a bit of time I'll look into this.

**Comment by michaelcspeed** [comment]
I think I fixed this (or at least improved this) in the latest version rolling out of the play store (3.0.22) - Would be grateful if someone can check :)

**Comment by lmicheloud** [comment]
I'm running /e/OS 1.17 (without google play services) on a Fairphone 3 and version 3.0.22 fixed the black screen for me. Hopefully it does the same for the others as well :)
Thanks a lot for the update ! :heart:

**Comment by scouech** [comment]
@jowodo @Studiedlist let us know if it's resolved for you. Cheers

**Comment by jowodo** [comment]
It works with version 3.0.13 on my android device (with google play service) and on my iOS 17.3.1 device.
