### ISSUE TITLE
[BUG] Background sound fade-in & fade-out

### ISSUE THREAD

**Issue by pramath98** [meditohq/medito-app#682]
**Describe the bug**
When we select background audio for meditation the audio starts and ends abruptly 

**To Reproduce**

1. Go to 'Any mediation' 
2. Click on 'background audio'
3. Start the meditation
4. Notice the audio, it starts and stops abruptly.

**Expected behavior**
It will be more pleasant if the audio starts with fade-in transition and ends with fade-out transition.

- Device: iPhone SE 2020
- OS: iOS 17.4
- Version: 3.0.13
  home page of the app)

**Comment by scouech** [comment]
@pramath98 we have an upcoming update on iOS which will fix that. I don't have a date yet but hopefully in the next few weeks!
