### ISSUE TITLE
[BUG] Persistent Medito icon on Android ambient display

### ISSUE THREAD

**Issue by d2718nis** [meditohq/medito-app#687]
**Describe the bug**
Android **ambient display** shows Medito app icon even after the mediation session was completed. The only way to remove it from there is to go to `Settings -> Apps -> App management -> Medito -> Force stop`.

**To Reproduce**

1. Open the Medito app
2. Start any type of mediation: daily, timer or any other; it doesn't matter
3. Either lock the screen or not, both of these ways would lead to the bug
4. Wait for the audio to finish
5. You may close the Feedback and "Show your support" screen or not, it won't affect the result
6. Lock the screen
7. You'll see the Medito icon on the ambient display

**Expected behavior**
There should be no notification icon on the Android ambient display if the audio is not playing at the moment.

**Screenshots**
Ambient screen
![medito-ambient](https://github.com/meditohq/medito-app/assets/18328279/eb85ac99-16b4-4b92-aa1d-50bff2accc42)

**Smartphone (please complete the following information):**

- Device: OnePlus 9 Pro (LE2125)
- OS: Oxygen OS 14.0 (Android 14, security update February 5, 2024)
- Version 3.0.22 build 30022

**Additional context**
There's also media controls on my Lock screen, even after the media has finished playing. I can get rid of it by swiping it aside, but it won't remove the icon from the ambient display.

Closing the app via swiping it off from the home screen also won't work. The only way to remove the icon is to force stop it in the settings.

**Comment by michaelcspeed** [comment]
Thanks for this excellent big report! I can confirm this has been fixed on the latest version of develop. I will try to publish to the Play Store this week.

**Comment by d2718nis** [comment]
Can confirm both media controls and ambient display icon fixed in version 3.0.27 build 30027. Thanks for swift response!
