### ISSUE TITLE
Add push notifications for 30-day challenges/streaks

### ISSUE THREAD

**Issue by milesmahon** [meditohq/medito-app#689]
Hello, I'd be interested in implementing push notifications. It particularly makes sense with the 30-day challenges to have a push notification that directly links to the next day of the challenge, or with The Medito Course, since it's for beginners trying to build a practice.

Could start small with just the challenges, providing a base for other notifications if desired.

**Comment by michaelcspeed** [comment]
There is now the option to set up daily reminders. They are basic but will do for now, so I will close this issue
