### ISSUE TITLE
System 'back' closes the app when on 'Explore' tab

### ISSUE THREAD

**Issue by d2718nis** [meditohq/medito-app#690]
**Describe the bug**
Pressing system 'back' button while being on the 'Explore' tab closes the app.

**To Reproduce**

1. Go to the 'Explore' tab
2. Use system 'back' button

**Expected behavior**
I feel like pressing the back button (or using a back swipe gesture, which is equivalent) should take me back to the 'Home' tab. I might be wrong in terms of UX/UI design, but that's what I automatically do, and I've had to reopen the app multiple times because of it :)

**Smartphone (please complete the following information):**

- Device: OnePlus 9 Pro (LE2125)
- OS: Oxygen OS 14.0 (Android 14, security update April 5, 2024)
- Version 3.0.29 build 30029

**Comment by rao-suraj** [comment]
I am interested in implementing this. I have read the contribution section and will follow the specified process. If needed, I can start working on it.

**Comment by michaelcspeed** [comment]
Ah this has been fixed recently. It will be available in the next release.
