### ISSUE TITLE
[Simple Feature Request] Apple Health Sync

### ISSUE THREAD

**Issue by ZepsiZola** [meditohq/medito-app#691]
I've been using the Medito app on my iPhone recently and I wanted to keep track of my "Mindful Minutes" with apple health. I looked around to see where I could link the Medito to the Health app as a data-source, but I found out that that isn't possible. All the other meditation apps have this simple feature and I'm sure it wouldn't be too hard to implement with Medito.

In short: I would like to be able to link Medito to Apple Health as a data-source so that I can track my meditation habits in the Health App.

Also this feature is in demand as it has been asked for in several places and there is not a clear reason why it is not implemented:
https://www.reddit.com/r/medito/comments/xduq8s/apple_health_sync/
https://www.reddit.com/r/medito/comments/1cx5om7/medito_app_should_be_in_the_data_source_list_for/
https://github.com/meditohq/medito-app/issues/176

**Comment by ChristianSch** [comment]
I'd also love to see this. Any reason this isn't implemented yet? Are there any blockers?

**Comment by ZepsiZola** [comment]
They've implemented it. Nice.
