### ISSUE TITLE
Using external audio player

### ISSUE THREAD

**Issue by Mattiakus** [meditohq/medito-app#692]
Heyho,
I have been trying to use medito with an external audio Player for a while and I have been struggeling tryna find a way to do that. I have tried to export the audio files by browsing the github repo and the android files but couldn't find anything useful. Would really appreciate some help. Thanks <3

**Comment by michaelcspeed** [comment]
We don't support that for all audio files but there are some on the website you could download

**Comment by Mattiakus** [comment]
> We don't support that for all audio files but there are some on the website you could download

Much thanks! Really appreciate it <3
